name: CI (Master)

env:
  JDK_CURRENT: 11
  DISTRIBUTION: zulu

on:
  push:
    branches:
      - master
      - 5.0.x

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: imply-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B clean install

  deploy:
    runs-on: imply-ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
          server-username: ${{ secrets.ARTIFACTORY_USER }}
          server-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: mvn --batch-mode -DskipTests deploy -s ci-settings.xml
