name: CI (PR)

env:
  JDK_CURRENT: 11
  DISTRIBUTION: zulu

on:
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.workflow_dispatch.inputs.dry-run }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: imply-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_CURRENT }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B clean install
